### ISSUE TITLE
ServiceFabric Issues with ASP.NET Core 2.0 - WebApp/WebAPI

### ISSUE THREAD

**Issue by grahamehorner** [Azure/service-fabric#16]
I'm getting the following error for ServiceFabric when using an ASP.NET Core 2.0 WebAPP ? 

Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures in_Node_2 API call: IStatelessServiceInstance.Open(); Error = System.MissingMethodException (-2146233069)
**Method not found: 'Void Microsoft.AspNetCore.Hosting.IWebHost.Start()'.**
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__14.MoveNext()

**Comment by anandvadul** [comment]
I hit the same issue and had to fall back into WCF - were you able to resolve this issue?

**Comment by grahamehorner** [comment]
Yes, I to resolve use kestrel and aspnet core preview 3 (myget feed) the issue is the Start method had been removed by the aspnet core team, but they have since re-implemented it after I logged an issues with them about the breaking change which was unintentional.
