### ISSUE TITLE
Standalone cluster installation failure on Windows Server 2016

### ISSUE THREAD

**Issue by phillipsj** [Azure/service-fabric#19]
I am running into several failures and I have been able to remove most of these, but I am still receiving the following:

Configuring machine 'x1'.
Configuring machine 'x2'.
Configuring machine 'x3'.
Machine x1 configured.
Machine x2 configured.
Machine x3 configured.
Running Fabric service installation.
Successfully started FabricInstallerSvc on machine x3
Successfully started FabricInstallerSvc on machine x1
Successfully started FabricInstallerSvc on machine x2
Timed out waiting for Installer Service to complete for machine x3. Investigation order: FabricInstallerService -> FabricSetup -> FabricDep
loyer -> Fabric
Timed out waiting for Installer Service to complete for machine x2. Investigation order: FabricInstallerService -> FabricSetup -> FabricDep
loyer -> Fabric
Timed out waiting for Installer Service to complete for machine x1. Investigation order: FabricInstallerService -> FabricSetup -> FabricDep
loyer -> Fabric
CreateCluster Error: System.AggregateException: One or more errors occurred. ---> System.ServiceProcess.TimeoutException: Timed out waiting for Install
er Service to complete for machine x3. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceControl
ler installerSvc)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`
2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 body
WithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.RunFabricServices(List`1 machines, FabricPackageType fabricPackageType)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine x3. Inves
tigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceControl
ler installerSvc)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine x2. Inves
tigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceControl
ler installerSvc)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #2) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine x1. Inves
tigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceControl
ler installerSvc)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

Trace folder already exists. Traces will be written to existing trace folder: C:\Users\x\Desktop\Microsoft.Azure.ServiceFabric.WindowsServer.5.
6.220.9494\DeploymentTraces
Cleaning up faulted installation.

**Comment by phillipsj** [comment]
Here is some info from the trace logs.

2017-07-10 18:07:10.288,Error   ,5176,FabricInstallerService.FabricUpgradeManager,Target information file exists. This would indicate that Fabric node open or Fabric uninstall didn't happen successfully. Rolling back..
2017-07-10 18:07:10.288,Noise   ,5176,Timer.CancelCalled,26bc0e65a10 cancel called, waitForCallbackOnCancel = false
2017-07-10 18:07:10.288,Noise   ,5176,Timer.CancelWait,26bc0e65a10 wait for cancel completion
2017-07-10 18:07:10.288,Info    ,5176,FabricInstallerService.FabricUpgradeManager,Rollback started with FabricDataRoot:C:\ProgramData\SF, FabricLogRoot:C:\ProgramData\SF\Log, FabricCodePath:C:\Program Files\Microsoft Service Fabric\bin\fabric\fabric.code, FabricRoot:C:\Program Files\Microsoft Service Fabric, TargetInformationFilePath:C:\ProgramData\SF\TargetInformation.xml, TargetInformationDescription:TargetInformationFileDescription { CurrentInstallation = WindowsFabricDeploymentDescription { IsValid = false, InstanceId = , MSILocation = , ClusterManifestLocation = , InfrastructureManifestLocation = , NodeName = , RemoveNodeState = 0, UpgradeEntryPointExe = , UpgradeEntryPointExeParameters = , UndoUpgradeEntryPointExe = , UndoUpgradeEntryPointExeParameters = , }TargetInstallation = WindowsFabricDeploymentDescription { IsValid = true, InstanceId = 0, MSILocation = C:\ProgramData\SF\ServiceFabric.cab, ClusterManifestLocation = C:\ProgramData\SF\clusterManifest.xml, InfrastructureManifestLocation = , NodeName = , RemoveNodeState = 0, UpgradeEntryPointExe = FabricSetup.exe, UpgradeEntryPointExeParameters = /operation:Install, UndoUpgradeEntryPointExe = , UndoUpgradeEntryPointExeParameters = , }}
2017-07-10 18:07:10.288,Warning ,5176,FabricInstallerService.FabricUpgradeManager,Rollback cannot be performed since the current installation is not present or invalid
2017-07-10 18:07:10.288,Noise   ,5176,General.AsyncOperation@26bc0e720d0,FinishComplete called with FABRIC_E_UPGRADE_FAILED
2017-07-10 18:07:10.288,Warning ,5176,FabricInstallerService.FabricUpgradeManager,Upgrade finished with error FABRIC_E_UPGRADE_FAILED

**Comment by duongthaiha** [comment]
We also have the same issue ? Any solution or workaround please?
